### ISSUE TITLE
TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by h0tbird** [app-registry/helm-plugin#23]
Find below mi environment details:
```
> helm registry version quay.io
Api-version: {u'cnr-api': u'0.2.7'}
Client-version: 0.4.0
```

```
> helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```

```
> kubectl version 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
> helm registry list quay.io | grep thevotingapp
quay.io/softonic/thevotingapp                   0.1.0      -            helm
```

I get the error below every time I try to install a package:
```
> helm registry install quay.io/softonic/thevotingapp
Pull package: softonic/thevotingapp... 
/tmp/softonic_thevotingapp_0.1.0.tar.gz
Traceback (most recent call last):
  File "bin/cnr", line 6, in <module>
  File "cnrclient/commands/cli.py", line 51, in cli
  File "cnrclient/commands/helm.py", line 32, in _install
  File "cnrclient/commands/helm.py", line 25, in exec_helm_cmd
  File "cnrclient/plugins/helm.py", line 99, in action
  File "cnrclient/plugins/helm.py", line 104, in _call
  File "subprocess.py", line 566, in check_output
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 1335, in _execute_child
TypeError: execv() arg 2 must contain only strings
Failed to execute script cnr
Error: plugin "registry" exited with error
```

**Comment by ant31** [comment]
Hi thx for report, 
A fix is going to be pushed (0.4.1)
Additionnaly  e2e tests will be added soon

**Comment by ant31** [comment]
The release is available. 
Note that the install/upgrade procedure have been updated: 
https://github.com/app-registry/appr-helm-plugin#install

**Comment by h0tbird** [comment]
Thank you! When will it be available via `pip install`?
```
/ # pip install cnr==0.4.1
Collecting cnr==0.4.1
  Could not find a version that satisfies the requirement cnr==0.4.1 (from versions: 0.0.1, 0.0.2, 0.3.5, 0.3.8)
No matching distribution found for cnr==0.4.1
```

**Comment by ant31** [comment]
it should be available now. sorry for that. 
I let you close once you confirmed that's working for you

**Comment by h0tbird** [comment]
Super! It works now.
Thank you @ant31
