### ISSUE TITLE
Unclear Error when Trying to Push from Incorrect Directory

### ISSUE THREAD

**Issue by alecmerdler** [app-registry/helm-plugin#29]
Assume below directory structure.
```
helm/
    |__nginx/
        |__Chart.yaml
        |__values.yaml
        |__...
```
When executing `helm registry push` from `helm/` (should be in `helm/nginx/`), receive an unclear error:
```
Traceback (most recent call last):
  File "bin/cnr", line 6, in <module>
  File "cnrclient/commands/cli.py", line 54, in cli
  File "cnrclient/commands/command_base.py", line 64, in call
  File "cnrclient/commands/command_base.py", line 69, in __call__
  File "cnrclient/commands/push.py", line 107, in _call
  File "cnrclient/commands/push.py", line 104, in _init
  File "cnrclient/commands/push.py", line 74, in _chart
  File "cnrclient/formats/helm/manifest_chart.py", line 20, in __init__
  File "cnrclient/formats/helm/manifest_chart.py", line 39, in _load_from_path
UnboundLocalError: local variable 'mfile' referenced before assignment
Failed to execute script cnr
Error: plugin "registry" exited with error
```
Would be better if CLI asked you to check that you are in the right directory containing a `Chart.yaml` file.

**Comment by tavisma** [comment]
A file not found error would be helpful

**Comment by aspett** [comment]
:100: This tripped me up for longer than I wish to admit.
