### ISSUE TITLE
helm registry dep --overwrite exits non-gracefully 

### ISSUE THREAD

**Issue by jeff-knurek** [app-registry/helm-plugin#40]
running `helm registry dep --overwrite` in a CI setup has a high risk of false failure

for example, 
* if the command is run in a directory without a requirements.yaml file:
```
Traceback (most recent call last):
  File "bin/appr", line 6, in <module>
  File "appr/commands/cli.py", line 53, in cli
  File "appr/commands/helm.py", line 43, in _dep_pull
  File "appr/plugins/helm.py", line 76, in build_dep
IOError: [Errno 2] No such file or directory: 'requirements.yaml'
```
where as `helm dependency update` results in a more graceful logging message:
`No requirements found in ...`

* if the requirements.yaml file only has appr dependencies, but no regular dependencies:
```
Traceback (most recent call last):
  File "bin/appr", line 6, in <module>
  File "appr/commands/cli.py", line 53, in cli
  File "appr/commands/helm.py", line 43, in _dep_pull
  File "appr/plugins/helm.py", line 81, in build_dep
TypeError: 'NoneType' object is not iterable
```
workaround of adding `dependencies: []`

**Comment by ant31** [comment]
This should be fixed in https://github.com/app-registry/appr/pull/78:

1. fix default `dependencies: []': https://github.com/app-registry/appr/pull/78/files#diff-3242e4036dcdf8c3ee865093b0397722R67
2. exit without error:
https://github.com/app-registry/appr/pull/78/files#diff-3242e4036dcdf8c3ee865093b0397722R60
